# Generated by Django 4.2.28 on 2026-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_genre_movie_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
